export default {
  almonds: require("../assets/images/icons/almonds.png"),
  spice: require("../assets/images/icons/spice.png"),
  fruit: require("../assets/images/icons/fruit.png"),
  hourglass: require("../assets/images/icons/hourglass.png"),
  distillery: require("../assets/images/icons/distillatory.png"),
  measuring: require("../assets/images/icons/measuring-cup.png"),
  percentage: require("../assets/images/icons/percentage.png"),
  whisky: require("../assets/images/icons/whisky.png"),
  friends: require("../assets/images/icons/friends.png"),
  message: require("../assets/images/icons/comment.png"),
  camera: require("../assets/images/icons/camera.png"),
  ginger: require("../assets/images/icons/ginger.png"),
  raisin: require("../assets/images/icons/raisins.png"),
  oak: require("../assets/images/icons/oak-leaf.png"),
  cask: require("../assets/images/icons/cask.png"),
  delete: require("../assets/images/icons/delete.png"),
  price: require("../assets/images/icons/price.png"),
  review: require("../assets/images/icons/review.png"),
  heart: require("../assets/images/icons/heart.png"),
  calendar: require("../assets/images/icons/calendar.png"),
  profile: require("../assets/images/icons/user.png"),
  collection: require("../assets/images/icons/bottle-rack.png"),
};
